name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Create Artifact Registry Repository
      run: |
        # Check if repository exists, if not create it
        if ! gcloud artifacts repositories describe cloud-run-source-deploy --location=us-central1 &>/dev/null; then
          echo "Creating Artifact Registry repository..."
          gcloud artifacts repositories create cloud-run-source-deploy \
            --repository-format=docker \
            --location=us-central1 \
            --description="Repository for Cloud Run deployments"
        else
          echo "Repository already exists, skipping creation."
        fi
      continue-on-error: true
      
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: my-app-dev
        region: us-central1
        source: .